# Generated by Django 4.2.8 on 2026-03-02 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['status', '-created_at'], name='listings_li_status_f5055b_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['farmer', 'status'], name='listings_li_farmer__b25cb2_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['category'], name='listings_li_categor_4dd4fc_idx'),
        ),
    ]
