# Generated by Django 4.2.8 on 2026-03-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('primary_crop_types', models.TextField(help_text='Comma-separated list of crop types')),
                ('province', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('gps_latitude', models.FloatField()),
                ('gps_longitude', models.FloatField()),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='farmers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Farmer Profile',
                'verbose_name_plural': 'Farmer Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
